---
image: archlinux:latest

stages:
  - test

lint:
  stage: test
  needs: []
  before_script:
    - pacman -Syu --needed --noconfirm make flake8 mypy python-black python-isort
  script:
    - make lint
  only:
    changes:
      - keyringctl
      - libkeyringctl/*
      - test/*

test:
  stage: test
  needs: []
  before_script:
    - pacman -Syu --needed --noconfirm make python sequoia-sq python-pytest
  script:
    - make test
  only:
    changes:
      - keyringctl
      - libkeyringctl/*
      - test/*

build_install:
  stage: test
  needs: []
  before_script:
    - pacman -Syu --needed --noconfirm make python sequoia-sq
  script:
    - ./keyringctl import --main master master-revoked
    - ./keyringctl import packager packager-revoked
    - make
    - make install PREFIX=/usr
    - pacman-key --init
    - pacman-key --populate archlinux
    - pacman-key --updatedb
    - pacman -Syu
